name: "プルリクエストテンプレート"
about: "変更の概要と目的を記載します"
title: ""
labels: ""
assignees: ""

body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 変更の概要を記載してください
      placeholder: 変更の概要

  - type: textarea
    id: changes
    attributes:
      label: 変更点
      description: 変更内容をリスト形式で記載してください
      placeholder: |
        - 変更点1の説明
        - 変更点2の説明
        - 変更点3の説明

  - type: textarea
    id: test_procedures
    attributes:
      label: テスト手順
      description: 変更点を確認するためのテスト手順を記載してください
      placeholder: |
        1. 手順1
        2. 手順2
        3. 手順3

  - type: textarea
    id: related_issues
    attributes:
      label: 関連するIssue
      description: 関連するIssueがあれば、そのリンクを記載してください
      placeholder: |
        - Issue 1: [リンク](#)
        - Issue 2: [リンク](#)

  - type: textarea
    id: others
    attributes:
      label: その他
      description: 追加の情報や注意点があれば記載してください
      placeholder: 追加情報

