name: プルリクエストテンプレート
description: プルリクエストの概要と詳細を記載するテンプレート
title: "[PR] タイトルを入力してください"
labels: []
assignees: []

body:
  - type: input
    id: pr-overview
    attributes:
      label: 概要
      description: このプルリクエストの概要を記載してください。変更内容や目的を簡潔に説明します。
      placeholder: 概要を入力してください
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 変更点

        - 変更点1の説明
        - 変更点2の説明
        - 変更点3の説明

        ## テスト手順

        変更点を確認するためのテスト手順を記載してください。

        1. 手順1の説明
        2. 手順2の説明
        3. 手順3の説明

        ## 関連するIssue

        関連するIssueがあれば、そのリンクを記載してください。

        - Issue 1: [リンク](#)
        - Issue 2: [リンク](#)

        ## その他

        追加の情報や注意点があれば記載してください。


