name: バグ報告
description: バグの報告用テンプレート
title: "[BUG] タイトルを入力してください"
labels: ["bug"]
assignees: []

body:
  - type: input
    id: overview
    attributes:
      label: 概要
      description: バグの概要を簡潔に説明してください
      placeholder: 概要を入力してください
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: バグを再現する手順を記載してください
      placeholder: 1. 手順1\n2. 手順2\n3. 手順3
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 本来期待される動作を記載してください
      placeholder: 期待される動作を入力してください
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 環境
      description: 使用しているOSやブラウザのバージョンを記載してください
      placeholder: 例: Windows 10, Chrome 89
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: その他
      description: 追加の情報があれば記載してください
      placeholder: その他の情報を入力してください



