name: バグ報告
description: バグの報告用テンプレート
title: "[BUG] タイトルを入力してください"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 概要

        バグの概要を簡潔に説明してください。

        ## 再現手順

        バグを再現する手順を記載してください。

        1. 手順1
        2. 手順2
        3. 手順3

        ## 期待される動作

        本来期待される動作を記載してください。

        ## スクリーンショット

        可能であれば、問題のスクリーンショットを添付してください。

        ## 環境

        - OS: [e.g. Windows 10]
        - ブラウザ: [e.g. Chrome 89]
        - バージョン: [e.g. 1.0.0]

        ## その他

        追加の情報があれば記載してください。


