name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install dependencies and run frontend tests
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        npm test

    # Setup Rust environment
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Install Diesel CLI
    - name: Install Diesel CLI
      run: cargo install diesel_cli --no-default-features --features postgres

    # Setup PostgreSQL service
    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '13'

    # Run backend tests
    - name: Run backend tests
      run: |
        cd backend
        cargo test